@contentType = application/json

#########################################
### Request: GET /utr-check/{utrNumber}
#########################################

### Path Parameter: utrNumber
@utrNumber = 4733150503


GET https://e0cc40oko48g8ckwg88swkcs.neohq.com/utr-check/{{utrNumber}}
Content-Type: {{contentType}}


