@contentType = application/json

################################
### Request: GET /utr-generate
################################


GET http://localhost:5283/utr-generate
Content-Type: {{contentType}}


