@contentType = application/json

################################
### Request: GET /utr-generate
################################


GET https://e0cc40oko48g8ckwg88swkcs.neohq.com/utr-generate
Content-Type: {{contentType}}


